### ISSUE TITLE
Request: customize transformation of symbols to SQL strings

### ISSUE THREAD

**Issue by eudoxia0** [fukamachi/sxql#27]
So, for Crane, I'd like to keep symbols as human-friendly as possible, which means avoiding unnecessary quoting when it's not needed (e.g., symbols that don't have dashes).

So, here's a feature request: a way to set a custom function that SxQL calls to transform a symbol to an SQL identifier.

**Comment by fukamachi** [comment]
Sounds reasonable. It'll be added in the near future.
