### ISSUE TITLE
Is backwards transform supported?

### ISSUE THREAD

**Issue by PosoSAgapo** [fukamachi/sxql#64]
Hi, thank you for your contribution to this repository. May I ask does this repository supports a SQL to CommonLISP transform? Or is it possible to transform SQL to CommonLISP based on this repository?

**Comment by jackcarrozzo** [comment]
To my knowledge, sxql doesn’t do any parsing of string statements into s expressions, no; it does allow you to pass raw sections of sql statement through though, I believe with :raw.

**Comment by fukamachi** [comment]
No such features.
I'm not sure it's what you want, but, as @jackcarrozzo mentioned, it's possible to embed a partial SQL string into an SxQL query with `:raw`.

**Comment by PosoSAgapo** [comment]
> No such features. I'm not sure it's what you want, but, as @jackcarrozzo mentioned, it's possible to embed a partial SQL string into an SxQL query with `:raw`.

Thank you for your reply, what I want is to transform SQL to s expressions. I will try to figure out other ways.
