### ISSUE TITLE
Correct use of set=

### ISSUE THREAD

**Issue by jim8786453** [fukamachi/sxql#7]
Apologies if there is a simple answer, I'm new to lisp and was just wondering how I should be doing this.  In the documentation the expected us of set= is like this:

```
(set= :id 123 :name "Jim") 
```

but I'd like to be able to use it like this:

```
(let ((data '(:id 123 :name "Jim"))) 
  (set= data))
```

I've tried using `values-list` when passing data to set= with no luck, and was just wondering how you would do it?

Thanks
Jim

**Comment by Juwebweb** [comment]
It's not possible to use ```apply```  on ```set=``` any more.
Indeed ```set=``` is now defined as a macro, no more a function. See : https://github.com/fukamachi/sxql/commit/6d6e3f2779ab5a7714ab317b9624bcfc6fe1ceed

Is there a new way to insert a row from a plist?

Cheers,

**Comment by Juwebweb** [comment]
Inspired from post https://github.com/fukamachi/sxql/issues/20, I ended up doing the following :
```
(let
  (
    (row '(:col-1 1 :col-2 2))
  )
  (with-connection (db)
    (execute
      (make-statement
        :insert-into :table
        (apply #'make-clause (cons :set= row))))))
```

The query is built with these ```make-``` functions so it's possible to use ```apply```. In my example, the query is executed using "datafly" library.

It's not an ideal solution but it does the job for now!

I believe this functionality should be available with no tricks, do you think it would make sense to create a ```set-row``` macro in the lib? 

I'm a lisper newbie but would be happy to contribute.
