### ISSUE TITLE
Returning multiple items from insert

### ISSUE THREAD

**Issue by diasbruno** [fukamachi/sxql#70]
Using `returning` (with multiple columns) on a `insert` statement generates incorrect query.

```lisp
(returning :id :name)
```

produces

```lisp
ID(`name`)
```

expected

```lisp
`id`, `name`
```

**Comment by fukamachi** [comment]
Sorry for the delay. I fixed it by #72.
Just a note for a workaround, `(sxql:returning (sxql:fields :id :name))` works expectedly.

**Comment by diasbruno** [comment]
Thanks, @fukamachi. #72 looks really good.
